apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example1
        release: example1
    spec:
      containers:
        - name: example1
          image: "nginx:1.14.0"
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: example1
      release: example1