
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.bar.com
  labels:
    app: {{ .Release.Name }}-crd
    release: {{ .Release.Name }}
    myLabel: testing123
spec:
  group: bar.com
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
    shortNames:
      - en
  scope: Namespaced
  version: v1